### ISSUE TITLE
Would you extract english string file(json) to make translation into korean? 

### ISSUE THREAD

**Issue by dakeshi** [MattyIce/steem-keychain#105]
Hi. I can not find out the english string file to support i18n in the repo. (If it has, where can I find it out?)

As you know, steem keychain get more focused after the releasing of SCT or JJM project on the steem blockchain. If it is possible to provide localized context for a new users, it will be better to enjoy their steem life.

Personally, I prefer to integrated it into Crowdin(translation management platform having free plan for the open source project) but if it is not possible to set it up, I'm just fine to take a translation with the original english json file.

**Comment by shawnpringle** [comment]
Take a look in _locales/ko/ in the repo.  The text looks like tofu to me.  It might be Korean.

**Comment by dakeshi** [comment]
steem keychain project has already integrated into Crowdin to support translation.
