### ISSUE TITLE
example page sending won't work

### ISSUE THREAD

**Issue by krtschmr** [MattyIce/steem-keychain#107]
as soon i click "send", nothing happens. just error message all the time. handshake is working tho

console  log
    transfer
    main.js?v=a:46 main js response - transfer
    main.js?v=a:47 {success: false, error: "incomplete", result: null, message: "Incomplete data or 
    wrong format", data: {…}, …}

**Comment by krtschmr** [comment]
```
 steem_keychain.requestTransfer("test", "testy", 1, "memo", "STEEM", function(response) {
        console.log('main js response - transfer');
        console.log(response);
    })
```

**Comment by stoodkev** [comment]
Please input 3 decimals for the amount
