### ISSUE TITLE
Feature Request: RPC Node Suggestions

### ISSUE THREAD

**Issue by therealwolf42** [MattyIce/steem-keychain#123]
Currently, the users have to change RPC nodes themselves. For example, in case of api.steemit.com being down, people have to know what node is working and where to change it.

That's too much for the average user. It would be better if the app, who is making the request, could check internally which nodes are working and then suggest a specific rpc node to be used.

Example - Curently:

- Bob is playing SteemMonsters
- Bob wants to transfer a card to Peter
- Bob approves the transaction with keychain, but api.steemit.com is down.
- Bob receives an error and is wondering what happened

Example - Then:

- Bob is playing SteemMonsters
- Bob wants to transfer a card to Peter
- Bob approves the transaction with keychain, but api.steemit.com is down.
- SteemMonsters knows that api.steemit.com is currently not functioning and is suggesting api.steemmonsters.com
- Keychain is accepting the RPC node as its found in an array of approvedRPCNodes (to prevent apps from suggesting malicious RPC nodes)
- Bob transferred the card successfully and wasn't even aware that api.steemit.com is down

**Comment by asgarth** [comment]
I would say that points 3 and 4 can be merged. Let's give SteemMonsters the option to set the RPC node. No point trying `api.steemit.com` first.

**Comment by stoodkev** [comment]
I ll do my best to have this done tomorrow!
