### ISSUE TITLE
Add an auto-lock timer option

### ISSUE THREAD

**Issue by MattyIce** [MattyIce/steem-keychain#21]
There should be an optional setting to set the extension to auto-lock after a certain amount of time. This will add additional security for those who want it.

**Comment by stoodkev** [comment]
Auto-lock after Unlock or after last action? 
First one might be easy, if the latter, what do we consider an action?

**Comment by MattyIce** [comment]
Hey, do you think you can use this to determine if the browser is "idle": https://developer.chrome.com/apps/idle

It looks like that can determine if the browser is idle for a specified amount of time, or if the machine is "locked".

**Comment by stoodkev** [comment]
Is it really what the users want though? 
If they keep using the browser (but not the extension), the wallet won t lock
