### ISSUE TITLE
Add an open source license to the repository

### ISSUE THREAD

**Issue by dhimmel** [MattyIce/steem-keychain#33]
Super excited about Steem Keychain and the increased security it will bring to the common Steem workflow! The [introductory post](https://busy.org/@yabapmatt/hate-putting-private-keys-into-websites-introducing-steem-keychain) mentions:

> The code for the extension is all open source and available [on Github here](https://github.com/MattyIce/steem-keychain)

However, I didn't see a `LICENSE` file in the repo / anything mentioned in the README. This is not ideal as [described here](https://choosealicense.com/no-permission/). Open source licenses, in addition to granting users the ability to modify and distribute the software, also have disclaimers such that should a user of the software have an issue the developers are not personally responsible.

There are many [OSI-approved licenses](https://opensource.org/licenses). Happy to answer any questions about their specific implications to the best of my ability (IANAL). Personally, I go with permissive licenses for my work such as MIT or BSD 3-Clause, but depending on your priorities copyleft licenses may be of interest.

**Comment by MattyIce** [comment]
You are right...totally forgot about that. License is added now, thank you!

**Comment by dhimmel** [comment]
Thansk @MattyIce for adding it in https://github.com/MattyIce/steem-keychain/commit/3b465747362735daf4dab340e88902ba4d6a7387. :clinking_glasses:
