### ISSUE TITLE
README: requestDelegation and requestPost/comment_options is missing

### ISSUE THREAD

**Issue by tchap** [MattyIce/steem-keychain#45]
README does not contain any mentions of `requestDelegation` and also `requestPost` is missing `comment_options` there.

**Comment by tchap** [comment]
@eonwarped I think that also you forgot to update README with the newly added methods in #51 and #52 ... This really sucks for the developers.

**Comment by eonwarped** [comment]
Sorry, small oversight. I did remember to add it to the example html though. Should be added soon to README. But do note it's not released yet (I think?).

**Comment by eonwarped** [comment]
Ohhh it does appear to be released.

**Comment by tchap** [comment]
@eonwarped No problem for me, I am checking the API source file directly, but newcomers can get confused a bit, because from README it looks like you cannot do much with this extension 😉
