### ISSUE TITLE
Add support for `claim_account` and `create_claimed_account`

### ISSUE THREAD

**Issue by steemchiller** [MattyIce/steem-keychain#64]
In case of an error when using `requestBroadcast` there is no error text being returned for some operations. `response.success` is false, but `response.error` is {} in some cases.

When I do a `claim_reward_balance` and there are no rewards to be claimed, it works as expected and the error text from the node is being returned, but when I try to claim an account with RC and I don't have enough RC available, the error is empty.

***Update:***
Seems like the operations `claim_account` and `create_claimed_account` are not being supported yet. I guess that's why the responses for these ops don't contain the error text.

Great work btw, I'm now using KeyChain on SteemWorld ;)

**Comment by stoodkev** [comment]
Hi! Sorry for late answer, did you manage to do what you wanted with the `requestBroadcast` method or do you think we need to add specific methods?

**Comment by steemchiller** [comment]
I'm not sure if the official steemjs lib is still outdated, but the steemjs.js you included in your project does not contain the new (after HF20) API methods. When you take a look at https://github.com/MattyIce/steem-keychain/blob/84f01fae480a1785d00a91afcd2fa6ad1a3178e6/vendor/steemjs.js#L15856 you see all supported methods and `claim_account` and `create_claimed_account` are not in there.

I have had the same problem on SteemWorld, therefore I added a few missing methods in my local steemjs code and am now only using my own version of steemjs. Of course, that's not the best way, because I can't use the official version anymore, but I needed an up-to-date version for my tools... :)

**Comment by steemchiller** [comment]
`claim_account` now works on Firefox with KC Version 1.5.7, but `create_claimed_account` still does not go through (loads infinitely, no error message being shown).

I used `requestBroadcast` with following op params:

~~~
[
   [
      "create_claimed_account",
      {
         "creator": "steemchiller",
         "new_account_name": "realchiller",
         "owner":
         {
            "weight_threshold": 1,
            "account_auths": [],
            "key_auths":
            [
               [
                  "STM8RnfpudkVifUi7wuFDBDAX3sK7L16ppKgDU23rz3PxVNrsgdcQ",
                  1
               ]
            ]
         },
         "active":
         {
            "weight_threshold": 1,
            "account_auths": [],
            "key_auths":
            [
               [
                  "STM87ZgwWgf8MqPaYusDWALfyUCL5Hkm7W2mDxq4vybgYEtFUFDMe",
                  1
               ]
            ]
         },
         "posting":
         {
            "weight_threshold": 1,
            "account_auths": [],
            "key_auths":
            [
               [
                  "STM67iaC91v3z5QEej4hNcNseR5TdNjb782CM3z9er6NU8YioXYxb",
                  1
               ]
            ]
         },
         "memo_key": "STM5wBcirQkt9dHjbdgZr4s8DLr3suE9VnM1JXw5Ahy4ZRrLHnaJB",
         "json_metadata": {},
         "extensions": []
      }
   ]
]
~~~

I tried to broadcast it without KC and it worked without any problems.
