### ISSUE TITLE
Port for Firefox

### ISSUE THREAD

**Issue by DaniellMesquita** [MattyIce/steem-keychain#66]

**Comment by DaniellMesquita** [comment]
@MattyIce

**Comment by MattyIce** [comment]
@DaniellMesquita This is definitely something we want to do but it's a matter of priorities and also funding to do it. If someone wants to take on the task and submit a PR we would be happy to review and merge it if it is done well.

**Comment by stoodkev** [comment]
Done : https://addons.mozilla.org/en-US/firefox/addon/steem-keychain/
