### ISSUE TITLE
Cannot read property 'request_id' of null

### ISSUE THREAD

**Issue by adasq** [MattyIce/steem-keychain#69]
Receiving `Cannot read property 'request_id' of null` while calling `requestPost`.

Over here: https://github.com/MattyIce/steem-keychain/blob/b22ed4008049d5ae493c3c9921884f72ddbe8e34/js/web_interface.js#L27 `request.detail` is null, so failing on line:

https://github.com/MattyIce/steem-keychain/blob/b22ed4008049d5ae493c3c9921884f72ddbe8e34/js/web_interface.js#L43

My environment:
`Version 72.0.3626.81 (Official Build) (64-bit)`
`Windows 7`

**Comment by stoodkev** [comment]
Please check that you've called the function correctly. I couldn't reproduce this bug with the information provided.

**Comment by adasq** [comment]
You should extend description of `steem_keychain.requestPost` in `README.md`, because it lacks last parameter, `comment_options`. That caused an error. Consider using an object rather than large number of parameters.
