### ISSUE TITLE
Allow to encrypt memo also when confirming a transfer

### ISSUE THREAD

**Issue by asgarth** [MattyIce/steem-keychain#72]
Currently it's possible to encrypt a memo when you start the transfer from keychain. If the transfer is triggered by the website the option is missing.

![selection_014](https://user-images.githubusercontent.com/182944/51996335-cc313180-24b4-11e9-8e4d-091c4bd2b897.jpg)

**Comment by nirvanaitsolutions** [comment]
Can keychain be used for escrow transactions?

**Comment by stoodkev** [comment]
@asgarth why not proposing this option directly on the website and then either passing the unencrypted / encrypted memo to Keychain?

**Comment by asgarth** [comment]
Because the main point of using keychain is that the website does not have the keys, so I cannot encrypt the memo to pass to Keychain.

**Comment by stoodkev** [comment]
Sorry I expressed myself poorly.
I meant you can have a checkbox on your website and depending on user input ask for an encrypted (or not ) transfer. If you add `#` at the begining of the memo, Keychain will attempt to encrypt it using Memo key.

**Comment by stoodkev** [comment]
Yep
