### ISSUE TITLE
Cannot remove a vote

### ISSUE THREAD

**Issue by asgarth** [MattyIce/steem-keychain#74]
It's not possible to remove a vote because the validation fail when the vote weight is ZERO.
```
error: "incomplete"
message: "Incomplete data or wrong format"
```

Problem is on the validation performed with `isFilled` because 0 equals the empty string.
Quick fix:
```
function isFilledWeight(obj) {
    return obj != undefined && obj != null && !isNaN(obj) && obj >= -10000 && obj <= 10000 && countDecimals(obj) == 0;
}
```

**Comment by stoodkev** [comment]
You can pass `"0"` as a String
