### ISSUE TITLE
Issue with requestVerifyKey data format

### ISSUE THREAD

**Issue by DSofter** [MattyIce/steem-keychain#78]
In order to let user login, I called `requestSignBuffer` first, and then called `requestVerifyKey`.

And here is what i got:

```
{
  "success": false,
  "error": "incomplete",
  "result": null,
  "message": "Incomplete data or wrong format",
  "data": {
    "request_id": 3,
    "type": "decode",
    "username": "todo",
    "message": "2009d24403857481951d1466ef16f026e9ec1afdde79248c5d252d7dffd766b85e3f375881e14786d5a3fc04716aeb66095a0a3cb6acf67fbfafeb3f06a0bc0618",
    "method": "Active"
  },
  "request_id": 3
}
```

Was there anything I was missing? Thanks!

**Comment by wusomba** [comment]
I have the same problem. But apart of this bug is it really needed to verify key? Because if user fail to requestSignBuffer it means he does not have keys anyway. So there is no point of storing it, just check if he can sign. Or maybe I don't get something?

**Comment by stoodkev** [comment]
The message needs to start with `#`

**Comment by stoodkev** [comment]
@wusomba indeed if you use requestSignBuffer you don't need to use this method.

**Comment by DSofter** [comment]
@wusomba @stoodkev Thanks guys!
