### ISSUE TITLE
Does keychain has a whitelist feature?

### ISSUE THREAD

**Issue by DSofter** [MattyIce/steem-keychain#79]
I was wondering if keychain has a whitelist feature? Don't want to pop up to user every time they vote.

**Comment by chrisli30** [comment]
For us it's transfer. We are looking to implement an auto-transfer function so user won't need to manually approve each transaction. EOS Scatter has a similar function. Of course we will have disclaimer upfront to get their consent.

**Comment by stoodkev** [comment]
There is a whitelist for every action that does NOT require active authority.
So in your case @DSofter that will not be an issue.
For safety reasons, we do not whitelist transfers and other active broadcasts @chrisli30

**Comment by chrisli30** [comment]
@stoodkev What's the main reason for Keychain to be conservative about opening whitelist transfer? Scatter has proved that EOS users are educated enough to understand the functionality and use at their own discretion. We have a game dapp and I think adding whitelist transfer will be a win-win situation for both of us. We'll try our best to drive users to use Keychain.

**Comment by chrisli30** [comment]
Is it an engineering resource issue? I'm happy to chat on Telegram if you are interested.
Telegram: @kezjo

**Comment by stoodkev** [comment]
Hi @chrisli30 and sorry for the (extremely) late answer. 
A whitelist on active authority could let an App empty a user account, and therefore we don t allow it, to stay on the safe side.
