### ISSUE TITLE
No Sticky Footer on Token Overview

### ISSUE THREAD

**Issue by RivalzZz88** [MattyIce/steem-keychain#84]
Hey Guys,

now it's the Time is got more and more tokens collected and when i'm scrolling in my Tokens Area i have more than 10 Tokens alread the Footer is not stickying at the bottom of the viewpanel as my example shown:

![image](https://user-images.githubusercontent.com/20746335/54705422-12ae1e80-4b3d-11e9-8290-f7962e65fe3b.png)

![ezgif-3-8c2c5399d0bb](https://user-images.githubusercontent.com/20746335/54705541-57d25080-4b3d-11e9-9621-56e332a8fce1.gif)

**Comment by MattyIce** [comment]
@stoodkev can you take a look at this when you get a chance? Simplest fix would just be to not show the witness vote message on this screen.
