### ISSUE TITLE
How to properly use `requestVerifyKey`?

### ISSUE THREAD

**Issue by FranticIch** [MattyIce/steem-keychain#85]
I'm having trouble using `requestVerifyKey` to verify a signed message.
```javascript
const keychain = window.steem_keychain;
keychain.requestSignBuffer('username', 'msg', 'Posting', function(response) {
    console.log(response);
        
    keychain.requestVerifyKey('username', response.reply, 'Posting', function(response) {
        console.log(response);
    });
});
```

This results in a `"Incomplete data or wrong format"` error.
#78 suggests adding a `#` to the message so if I'm not mistaken it would be `requestVerifyKey('username', '#' + response.reply, 'Posting'`.

This solves the error but does not result in a successfull callback, but in another error
```javascript
{
    data: {
        key: 'posting',
        message: '#1f716b3247b63179ed74a2a1ba7a9b098ac4e895986f475fdcfee9cb83e08f0b9e1284d6022ed072a1641cfb6268022e9dbe7c62c874433d42774a42a084c0e870',
        method: 'Posting',
        request_id: 2,
        username: 'username'
    },
    error:  'decode_error',
    message: 'Could not verify key.',
    request_id: 2
    result: null,
    success: false
        
}
```

What exactly am I doing wrong and what is the purpose of starting the message with an `#`?

**Comment by stoodkev** [comment]
`verifyKey` simply checks if you can decode a message with a given key.
Steps:
1) Encode whatever message using user's public key.
2) Ask the user to decode it using `requestVerifyKey`
3) check the value returned against the message you ve encoded.
