### ISSUE TITLE
Add support for stored accounts enumeration

### ISSUE THREAD

**Issue by VIM-Arcange** [MattyIce/steem-keychain#89]
It would be nice to be able to enumerate the list of accounts available in the wallet (either all or filtered by key type)

The API prototype would be
```
steem_keychain.requestAccounts(key_type, function(response) {
    console.log(response);
});
````

The values for "key_type" can be: "All", "Memo", "Posting", or "Active".

This could be useful for users with multiple account. 
Applications would be  able to propose a list with the account user want to use or login in with.

**Comment by stoodkev** [comment]
As previously discussed over Discord, we do not do this due to security considerations.
