### ISSUE TITLE
Signing with Keychain doesn't work on Firefox Android

### ISSUE THREAD

**Issue by nirvanaitsolutions** [MattyIce/steem-keychain#95]
I am able to install steem-keychain on Android mobile phone on Firefox browser. I can view and make transfers with the extension but signing in to apps doesn't work.
It could be related to external pop up since keychain opens a new window for signing a txn.

**Comment by stoodkev** [comment]
Hi! We dont provide support for Firefox for Android.
You can check @roelandp 's SteemWallet on Android that wraps keychain to be used with many websites.

**Comment by roelandp** [comment]
@nirvanaitsolutions thats https://steemwallet.app :)
