### ISSUE TITLE
Getting Invalid Params when I try sending Tokens from my Site

### ISSUE THREAD

**Issue by Desmond41** [MattyIce/steem-keychain#99]
When` I try sending the token I get successful transaction made from the steem Keychain extension but when I check the balance of the token, the tokens will still be the same amount. I decided to check it oun steem Engine block Explorer and I saw that is given me invalid params. 
Below is the code I use for the transfer of the token:

`<body>
<h3>Send Tokens</h3>
    <input type="text" placeholder="username" id="tokens_username" />
    <input type="text" placeholder="to" id="tokens_to" />
    <input type="text" placeholder="1.000" id="tokens_qt" />
    <input type="text" placeholder="tokens" id="tokens_unit" />
    <input type="text" placeholder="memo" id="tokens_memo" />
    <button id="sendTokens">Send</button>

    <script src="jquery.js"></script>
    <script src="main.js?v=a"></script>
</body>`

**Comment by wehmoen** [comment]
The issue seems to be that keychain always sends the token quantity as a Number type while it has to be a String: https://steem-engine.rocks/tx/161573b481efe0bd65ad8e24f1e2d1fac32a8024

**Comment by Desmond41** [comment]
Then the I think they have to fix that

**Comment by stoodkev** [comment]
This was fixed in 22b3f11050ba5172470da789744e25c0d39e9086
